name: 'NonGrate Container Action Template'
description: 'Get started with Container actions'
author: 'GitHub'
inputs: 
  who-to-greet:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: './Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
