name: Build and test
on: push

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        
      - name: Run container
        id: hello-action
        uses: ./DOCKERFILE
