name: Build and test
on: push

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        
      - name: Run container
        uses: actions/Actions_Test@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: hello-action
        with:
          who-to-greet: "Me!"
